// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgrWGvaACUOliee-7Hv7l03h1mPZKI0w',
    appId: '1:831166027593:web:7efc62ffe3329b07ab6c98',
    messagingSenderId: '831166027593',
    projectId: 'code-craft-bb5b1',
    authDomain: 'code-craft-bb5b1.firebaseapp.com',
    storageBucket: 'code-craft-bb5b1.appspot.com',
    measurementId: 'G-DPZTP8VQ1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMcme-KGcidrSdnAjr7dtGGLWvymReU0',
    appId: '1:831166027593:android:f93618dd120d72acab6c98',
    messagingSenderId: '831166027593',
    projectId: 'code-craft-bb5b1',
    storageBucket: 'code-craft-bb5b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1lG3Shw28nkyaC7Co2nonai23BQxuyEw',
    appId: '1:831166027593:ios:5106196f5dc87790ab6c98',
    messagingSenderId: '831166027593',
    projectId: 'code-craft-bb5b1',
    storageBucket: 'code-craft-bb5b1.appspot.com',
    iosBundleId: 'dev.faun.codecraft',
  );
}
